### ISSUE TITLE
[BUG] Unable to open the app anymore

### ISSUE THREAD

**Issue by gianpaolodn** [immuni-app/immuni-app-android#280]
**Describe the bug**

Suddenly, yesterday, after resuming the phone from standby the crash pop-up appeared. The app immuni crashed.
Now it keeps crashing everytime i try to open it, but i do not know if i can delete it and reinstall it without losing my tracing contacts.

I did connect my phone to android studio and this seems to be the reason of the crash:

```
2020-09-30 09:39:13.629 1874-2348/? E/ndroid.systemu: No package ID ff found for ID 0xffffffff.
2020-09-30 09:39:13.629 1874-2348/? E/IconLoader: Could not find icon drawable from resource
    android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
        at android.content.res.Resources.getDrawable(Resources.java:827)
        at com.android.systemui.shared.recents.model.IconLoader.createNewIconForTask(IconLoader.java:118)
        at com.android.systemui.shared.recents.model.IconLoader.getAndInvalidateIfModified(IconLoader.java:94)
        at com.android.systemui.shared.recents.model.RecentsTaskLoader.getAndUpdateActivityIcon(RecentsTaskLoader.java:325)
        at com.android.systemui.shared.recents.model.RecentsTaskLoadPlan.executePlan(RecentsTaskLoadPlan.java:188)
        at com.android.systemui.shared.recents.model.RecentsTaskLoader.loadTasks(RecentsTaskLoader.java:173)
        at com.android.systemui.recents.RecentsImpl$TaskStackListenerImpl.onTaskStackChangedBackground(RecentsImpl.java:184)
        at com.android.systemui.shared.system.TaskStackChangeListeners.onTaskStackChanged(TaskStackChangeListeners.java:80)
        at android.app.ITaskStackListener$Stub.onTransact(ITaskStackListener.java:50)
        at android.os.Binder.execTransact(Binder.java:731)
```

**To Reproduce**

Just open the app

**Expected behaviour**

I expect the app opens and tell me everything is fine

**Screenshots**

.

**Smartphone (please complete the following information):**

- Device: Sony Xperia XZ2  compact (H8314)
- OS: Android 9
- Version 1.5.0

**Additional context**

**Comment by gianpaolodn** [comment]
Reinstalling the app, solved the issue. 

Did i lose all tracing contacts or the os store all of them?

**Comment by ilovelinux** [comment]
If you uninstalled it, you probably did. Please, close this issue since it has been "solved"

**Comment by mirh** [comment]
I'm having the same problem with the same hardware and even on latest 2.1.1. I sent even a bug report yesterday night. 
If this is recurrent, we may as well try to fix it.
